(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var q1=function(a){a.W("cardstatechange",a.Zg()&&a.Fj()?1:0)},r1=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},RGa=function(a){var b=g.tg(a);
a=g.zg(a);return new g.bg(b.x,b.y,a.width,a.height)},SGa=function(a){return Math.pow(a,3)},TGa=function(a){return 3*a*a-2*a*a*a},u1=function(a){a=g.Pa(a);
delete s1[a];g.Pb(s1)&&t1&&t1.stop()},VGa=function(){t1||(t1=new g.J(function(){UGa()},20));
var a=t1;a.isActive()||a.start()},UGa=function(){var a=g.Sa();
g.Cb(s1,function(b){WGa(b,a)});
g.Pb(s1)||VGa()},v1=function(a,b,c,d){g.Cn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.B=null},WGa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.B);a.B=b;XGa(a,a.progress);1==a.progress?(a.gb=0,u1(a),a.onFinish(),a.Dt()):a.wc()&&a.Oy()},XGa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},YGa=function(a,b){g.yl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.gb},w1=function(a,b,c,d,e){v1.call(this,b,c,d,e);
this.element=a},x1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
w1.call(this,a,b,c,d,e)},y1=function(a){g.F.call(this);
this.i=a||window;this.l=[]},z1=function(a){return a.baseUrl||null},A1=function(a,b){return g.Ke(g.Pc(a,b,void 0),function(c){return!!c})},ZGa=function(a,b,c){function d(ya){var Ya,Gc,of,Va=ya.hovercardButton;
if(!Va)return null;Va=Va.subscribeButtonRenderer;if(!Va)return null;var Me=f(Va.unsubscribedButtonText),Hc=f(Va.subscribedButtonText);if(Va.subscribed){var Al=f(Va.subscriberCountWithUnsubscribeText);var Kj=f(Va.subscriberCountText)}else Al=f(Va.subscriberCountText),Kj=f(Va.subscriberCountWithSubscribeText);var Vf=null;return ya.signinEndpoint&&(Vf=r1(ya,"signinEndpoint","webNavigationEndpointData","url"),Vf||(Vf=null===(of=null===(Gc=null===(Ya=Va.signInEndpoint)||void 0===Ya?void 0:Ya.commandMetadata)||
void 0===Gc?void 0:Gc.webCommandMetadata)||void 0===of?void 0:of.url),!Vf)?null:Me&&(Hc||Vf)?{subscribed:Va.subscribed,subscribeText:Me,subscribeCount:Al,unsubscribeText:Hc,unsubscribeCount:Kj,enabled:Va.enabled,signinUrl:Vf,classic:ya.useClassicSubscribeButton}:null}
function e(ya){if(ya){var Ya=[],Gc=ya.videoId;Gc&&Ya.push("v="+Gc);(Gc=ya.playlistId)&&Ya.push("list="+Gc);(ya=ya.startTimeSeconds)&&Ya.push("t="+ya);return"/watch?"+Ya.join("&")}}
function f(ya){if(!ya)return null;var Ya=ya.simpleText;return Ya?Ya:ya.runs?g.Pc(ya.runs,function(Gc){return Gc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,A=null,E=null,I=null,H=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=r1(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):A=f(b.subscribersText)}else"WEBSITE"===
h?((E=r1(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(H=f(b.additionalFeesText)),(n=r1(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=r1(b,"title","accessibility","accessibilityData","label");var U=b.endpoint?b.endpoint.clickTrackingParams:null,N="";if(b.metadata){var fa=f(b.metadata);fa&&(N=fa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:N,callToAction:f(b.callToAction),
PF:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:A,isSubscribe:x,targetUrl:m||null,qO:n,Nd:U?{itct:U}:null,QS:p,Gr:a?a:null,tO:b.isPlaceholder,impressionUrls:A1(b.impressionUrls||[],z1),iO:A1(b.hovercardShowUrls||[],z1),clickUrls:A1(l.loggingUrls||[],z1),visualElement:g.zu(b.trackingParams),
productPrice:I,additionalFeesText:H}},B1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:A1(a.impressionUrls||[],z1),elements:A1(a.elements||[],function(d,e){return ZGa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.zu(a.trackingParams));return c},C1=function(a){g.dM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.V=!0;this.G=0;a=a.T();this.L=g.BD(a)||g.FD(a);this.events=new g.TL(this);g.G(this,this.events);this.events.N(this.player,g.Yv("creatorendscreen"),this.zd);this.events.N(this.player,g.Zv("creatorendscreen"),this.We);this.events.N(this.player,"resize",this.sb);this.events.N(window,"focus",this.WR);this.load();var b=g.Fe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ei(this,function(){g.Je(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},$Ga=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},D1=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},aHa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=B1(f,$Ga(a))));E1(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.vn;d&&(c.postParams={ad_tracking:d});if(b=g.eja(b))if(b=g.Ic(b),b=g.Cc(b))a.u=g.wp(b,c)},E1=function(a,b,c){c=void 0===c?!0:c;
a.player.Ye("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&bHa(a);c=[];d=new g.Vv(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",K:"ytp-ce-shadow"}),g.GL(a.player,a.l.element,4),a.B=new g.xK(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=cHa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.GL(a.player,f.element,4);var h=new g.Vv(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);dHa(a,f,e)}else g.Ru(new g.zs("buildEndscreenElement null",
e))}a.player.Dd(c);a.sb()}},bHa=function(a){var b=g.Du(),c=g.Fu();
c&&b&&a.endscreen.visualElement&&g.ev(c,b,a.endscreen.visualElement)},cHa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Gr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:F1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:G1(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-video-title"].concat(g.ma(c)),U:{dir:g.In(b.title||
"")},oa:b.title},{D:"div",K:"ytp-ce-video-duration",oa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Gr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:F1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:G1(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-playlist-title"].concat(g.ma(c)),U:{dir:g.In(b.title||"")},oa:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Gr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ca:["ytp-ce-channel-title","ytp-ce-link"],U:{href:G1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.In(b.title||"")},oa:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{D:"div",Ca:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:F1(b)}]};c=new g.V(c);var d=g.re(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Nd.itct}else e="endscreen",f=null;e=new g.kN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ca:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Gr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.In(b.title||"")},oa:b.title},{D:"div",K:"ytp-ce-website-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-website-goto","ytp-ce-link"],U:{href:G1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:F1(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:eHa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={D:"div",Ca:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Gr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.In(b.title||"")},oa:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:G1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:F1(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.V(a)}b.tO&&g.K(c.element,"ytp-ce-placeholder");return c},F1=function(a){if(a.PF)var b=a.PF.thumbnails;
return eHa(b?b[b.length-1].url:null)},eHa=function(a){return a?{style:"background-image: url("+a+")"}:{}},dHa=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),H1(a,c.id,!0)):(g.zn(b.element,"ytp-ce-force-expand"),g.zn(b.element,"ytp-ce-element-hover"),H1(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Pa("mouseenter",function(){I1(a,b,c)});
b.Pa("mouseleave",function(){J1(a,b,c)});
a.player.T().i||b.Pa("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){fHa(a,c,m)});
b.Pa("keypress",function(m){fHa(a,c,m)});
b.Pa("focus",function(){I1(a,b,c)});
b.Pa("blur",function(){J1(a,b,c)});
b.Pa("touchstart",function(){I1(a,b,c)});
var l=g.te("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.zn(b.element,"ytp-ce-element-hover");g.zn(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.te("ytp-sb-subscribe",b.element));d(g.te("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",h)},fHa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.xn(d,"ytp-ce-element");){g.xn(d,"subscribe-label")&&K1(a,b);
if(g.xn(d,"ytp-ce-channel-subscribe"))return;d=g.Le(d)}if(!d||g.xn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])J1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.QS)K1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Ic(G1(a,b.targetUrl)),c=g.Cc(c),g.AI(c,void 0,b.Nd);else{var e=a.player.getVideoData().C,f=function(){var h=G1(a,b.targetUrl),l=b.Nd,m=g.cp(h);e&&m&&(m.v||m.list)?a.player.dj(m.v,l,m.list,!1):g.zI(h,l)};
K1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},G1=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.jE(a)+b}else return"";return b},I1=function(a,b,c){g.xn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),L1(a,c.iO),H1(a,c.id,!0))},J1=function(a,b,c){g.zn(b.element,"ytp-ce-element-hover");
g.zn(b.element,"ytp-ce-force-expand");H1(a,c.id,!1)},H1=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.L(a.i[e].element,"ytp-ce-element-shadow-show",c)},L1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||D1(a))c&&c();else{b=gHa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Nq(b[a],d)}},K1=function(a,b,c){L1(a,b.clickUrls,c);
(a=g.Fu())&&b.qO&&g.hv(a,b.visualElement)},gHa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(hHa(b[d],c));return a},hHa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},iHa=function(a){return Array.isArray(a)&&a.length?a[0]:a},M1=function(a){return"string"===typeof a?a:""},N1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jHa=function(a){this.externalId=a},kHa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},O1=function(a){return a.value?a.value:null},P1=function(a){if(!a)return null;
var b=g.Ic(M1(a.value));b=g.Cc(b);if(!b)return null;var c=N1(a.target,lHa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new kHa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},mHa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},pHa=function(a){if(!a)return null;
var b=N1(a.type,nHa),c=N1(a.trigger,oHa),d=iHa(a.url);d=P1(d?d:null);a=iHa(a.subscribeData);var e=a?a:null;e?(a=M1(e.external_user_id),e=M1(e.subscription_token),a=a&&e?new jHa(a):null):a=null;return b?new mHa(b,c,d,a):null},qHa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},sHa=function(a){return(a=rHa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},rHa=function(a,b){return g.db(a.action,b,void 0)},tHa=function(a,b){this.context=a;
this.i=b},R1=function(a){return a.customMessage?Q1("div","iv-card-message",a.customMessage):""},S1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},S:c}},T1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Q1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},Q1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.In(c);return{D:a,U:b,oa:c}},uHa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Zu&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Zu+");");c.dir=g.In(a.customMessage);var d=[{D:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ca:b,U:c,S:d}},U1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Nd,c.tracking.click,5)}},vHa=function(a,b){this.merchant=a;
this.price=b},wHa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},xHa=function(a,b){return b?b:wHa(a)?"current":"new"},V1=function(a,b){g.F.call(this);
var c=this;this.element=a;this.context=b;this.Wa=!1;this.Ga=new Map;this.Na=new Map;this.context.I.addEventListener(g.Yv("annotations_module"),function(d){(d=c.Ga.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Zv("annotations_module"),function(d){(d=c.Na.get(d))&&d.apply(c)})},W1=function(a,b,c,d,e,f,h){a.context.i.Pa(b,"click",function(l){a.Py(c,d,e,f||[],h||0,l)});
a.context.i.Pa(b,"touchstart",function(){a.Wa=!1});
a.context.i.Pa(b,"touchmove",function(){a.Wa=!0})},yHa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},X1=function(a,b,c){return{IG:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
AJ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Mx:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},$1=function(a,b,c){V1.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Fa=this.eb=this.u=this.Rd=!1;this.ma=null;this.cards=[];this.Ya=this.L=this.Aa=this.C=this.Da=this.i=null;this.X=[];this.J=this.Zd=this.xa=null;this.G=0;this.va=new g.J(g.Ja,c.B.Cc?4E3:3E3);g.G(this,this.va);this.Xa=new g.J(g.Ja);g.G(this,this.Xa);this.Y=new tHa(c,function(e,f,h,l,m,n){W1(d,e,f,h,l,m,n)});
this.V=new g.V({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ca:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.G(this,this.V);this.B=this.V.element;this.Qa=new g.xK(this.V,330);g.G(this,this.Qa);this.bb=g.te("iv-drawer-header-text",this.B);this.l=g.te("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.eb&&Y1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.eb=d.u)&&Z1(d)})},zHa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){Y1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){Z1(a)});
var c=b.headerText;g.Re(a.bb,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.xa=g.zu(b.trackingParams);a.J=g.zu(b.closeTrackingParams);a.Zd=g.zu(b.iconTrackingParams)},AHa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.ew(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Nd:a2(a,c,b,d),sponsored:!1,tracking:X1(d,e,d.command),Hk:d.trackingParams?g.zu(d.trackingParams):null,ci:e.trackingParams?
g.zu(e.trackingParams):null,Zd:f&&f.trackingParams?g.zu(f.trackingParams):null,imageUrl:b2(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.ew(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Zu:null,title:d.title?g.ew(d.title):"",customMessage:d.callToAction?g.ew(d.callToAction):"",url:d.command.urlEndpoint.url?P1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};c2(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.ew(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Nd:a2(a,c,b,d),sponsored:!1,tracking:X1(d,e,d.endpoint),Hk:d.trackingParams?g.zu(d.trackingParams):null,ci:e.trackingParams?g.zu(e.trackingParams):null,Zd:f&&f.trackingParams?g.zu(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.ew(d.customText):null,LI:b2(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.ew(d.channelName):"",metaInfo:[d.subscriberCountText?g.ew(d.subscriberCountText):""],url:P1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};c2(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.ew(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Nd:a2(a,c,b,d),sponsored:!1,tracking:X1(d,e,d.action),Hk:d.trackingParams?g.zu(d.trackingParams):null,ci:e.trackingParams?g.zu(e.trackingParams):null,Zd:f&&f.trackingParams?g.zu(f.trackingParams):
null,xu:b2(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.ew(d.customMessage):null,playlistVideoCount:g.ew(d.playlistVideoCount),title:d.playlistTitle?g.ew(d.playlistTitle):"",metaInfo:[d.channelName?g.ew(d.channelName):"",d.videoCountText?g.ew(d.videoCountText):""],url:P1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:yHa(d.action)})};c2(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.ew(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Nd:a2(a,c,b,d),sponsored:!1,tracking:X1(d,e,d.action),Hk:d.trackingParams?g.zu(d.trackingParams):null,ci:e.trackingParams?g.zu(e.trackingParams):null,Zd:f&&f.trackingParams?g.zu(f.trackingParams):null,xu:b2(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.ew(d.lengthString):null,customMessage:d.customMessage?g.ew(d.customMessage):null,title:d.videoTitle?g.ew(d.videoTitle):"",metaInfo:[d.channelName?g.ew(d.channelName):"",d.viewCountText?g.ew(d.viewCountText):""],isLiveNow:!!d.badge,url:P1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:yHa(d.action)})};c2(a,b)}a.G++},b2=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},a2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},CHa=function(a,b){if(b=BHa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Je(b.Iz),g.lb(a.cards,b),a.ev(),d2(a)},Y1=function(a,b,c){if(!a.u){a.Qa.show();
a.Da=new g.J(function(){g.K(a.context.I.getRootNode(),g.wS.IV_DRAWER_OPEN)},0);
a.Da.start();a.ma=g.Vp(a.l,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.Fu();d&&a.xa&&a.J&&g.fv(d,[a.xa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.nH||(f.nH=!0,DHa(a.context.logger,f.card.tracking.IG,b)),d&&g.fv(d,[f.card.Hk]);q1(a.I);c&&(a.C=new g.J(function(){a.Aa=a.L;a.Ya.focus()},330),a.C.start())}},Z1=function(a){a.u&&(a.Qa.hide(),g.Wp(a.ma),a.ma=null,g.zn(a.context.I.getRootNode(),g.wS.IV_DRAWER_OPEN),a.u=!1,q1(a.I),a.C&&a.C.stop(),a.C=new g.J(function(){a.Aa&&(a.Aa.focus(),a.Aa=null)},330),a.C.start())},
FHa=function(a){g.yn(a.element,[g.wS.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.GL(a.I,a.B,5);EHa(a);a.L=g.te("ytp-cards-button",a.I.getRootNode());a.Ya=g.te("iv-drawer-close-button",a.B);a.Rd=!0},EHa=function(a){var b=g.te("iv-drawer-close-button",a.B);
a.context.i.Pa(b,"click",a.YM,a);a.context.i.Pa(a.l,"touchend",function(){a.va.start()});
a.context.i.Pa(a.l,"scroll",a.kN,a);a.context.l.subscribe("onHideControls",function(){a.Fa=!0});
a.context.l.subscribe("onShowControls",function(){a.Fa=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Fa=g.xn(a.I.getRootNode(),"ytp-autohide")});
a.X.push(g.Uq("iv-button-shown",a.AO,a));a.X.push(g.Uq("iv-button-hidden",a.zO,a));a.X.push(g.Uq("iv-teaser-shown",a.CL,a));a.X.push(g.Uq("iv-teaser-hidden",a.CO,a));a.X.push(g.Uq("iv-teaser-clicked",a.BL,a))},c2=function(a,b){a.Rd||FHa(a);
CHa(a,b.id);var c=GHa(a,b);if(c){var d={card:b,Iz:c.element,nH:!1},e=HHa(a,d);g.sb(a.cards,e,0,d);c.ya(a.l,e);a.ev();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,d2(a),IHa(a,d),Y1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&JHa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){JHa(a,d)}),d2(a))}},GHa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=uHa(b);c={D:"div",Ca:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?O1(b.url)||"":""},S:[S1(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[Q1("h2",void 0,b.title),d]}]}]};c=new g.V(c);U1(a,g.se("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Ca:["iv-card","iv-card-channel"],S:[{D:"a",Ca:["iv-click-target"],U:{href:O1(b.url)||"","data-ytid":b.channelId},S:[S1(b.LI),
{D:"div",K:"iv-card-content",S:[R1(b),{D:"h2",K:"iv-card-primary-link",oa:b.title},T1(b)]}]}]},c=new g.V(c),U1(a,g.se("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Ca:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:O1(b.url)||""},S:[S1(b.xu,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[R1(b),Q1("h2","iv-card-primary-link",b.title),T1(b)]}]}]},c=new g.V(c),
U1(a,g.se("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.ib(b.offers);c=["iv-card"];d="";var f=uHa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",oa:f.merchant}),f={D:"div",S:e});e=b.url?O1(b.url)||"":"";c={D:"div",Ca:c,U:{tabindex:"0"},S:[{D:"a",Ca:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Patrocinado",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",oa:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},S:[Q1("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Fe("span");g.Re(d,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
c.Xc(d,"adInfo");U1(a,g.se("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ca:["yt-badge","yt-badge-live"],oa:"EN DIRECTO AHORA"}:null,d={D:"div",Ca:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:O1(c))||""},S:[S1(b.xu,d),{D:"div",K:"iv-card-content",S:[R1(b),Q1("h2","iv-card-primary-link",b.title),T1(b),f]}]}]},
c=new g.V(d),U1(a,g.se("iv-click-target",c.element),b,b.url),c;default:return null}},HHa=function(a,b){if(0===a.cards.length)return 0;
a=g.eb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},KHa=function(a){return a.i?"productListing"===a.i.card.type:g.gh(a.cards,function(b){return"productListing"===b.card.type})},d2=function(a){g.L(a.I.getRootNode(),"ytp-cards-shopping-active",KHa(a))},JHa=function(a,b){if(!g.xn(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Fu(),d=a.i?a.i.card.Zd:a.Zd;
c&&d&&g.gv(c,[d]);a.i=b;d2(a)}if(c="none"!=a.element.style.display)g.R(a.context.I.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Kq(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Xa.isActive()||((!a.u||!a.va.isActive()&&a.Fa)&&IHa(a,b),a.Xa.start(910+b.card.teaserDurationMs))}},
IHa=function(a,b){a.V.wb?(b=new v1([0,
a.l.scrollTop],[0,b.Iz.offsetTop],600,TGa),a.context.u.Pa(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Pa(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(a.V.Vb(!0),a.l.scrollTop=b.Iz.offsetTop,a.V.Vb(!1))},e2=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},BHa=function(a,b){return g.db(a.cards,function(c){return c.card.id===b})},f2=function(a,b,c){V1.call(this,a,b);
this.annotation=c;this.isActive=!1},LHa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},g2=function(a,b,c){f2.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},MHa=function(a,b){var c=void 0===c?0:c;
var d=RGa(b).width;g.rg(b,d);c=new x1(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,SGa);g.G(a,c);a.context.u.Pa(c,"begin",function(){g.Ag(b,!0)});
c.play()},PHa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ca:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({D:"div",Ca:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.kN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.I),a.i.ya(d));var f=a.createElement({D:"div",Ca:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ca:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ag(h,!1);var l=a.createElement({D:"div",Ca:["branding-context-container-outer"]});l.appendChild(h);g.jg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){NHa(a,h,l)},500);
g.G(a,a.u);a.context.i.Pa(a.element,"mouseover",function(){OHa(a,h,l,f,b.image_height)});
a.context.i.Pa(a.element,"mouseout",function(){a.u.start()})}},OHa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.zg(b);a.i||(b.style.width=g.qg(f.width,!0),c.style.width=g.qg(f.width,!0));g.jg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.jg(d,"right","1px");a.B=!0;g.Ag(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},NHa=function(a,b,c){g.zn(a.element,"iv-branding-active");
a.G=new g.J(function(){g.Ag(b,!1);a.i||(c.style.width=g.qg(0,!0))},250);
a.G.start();a.B=!1},QHa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},h2=function(a,b,c){f2.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.V=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ca:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Ag(d.u,!1);g.Ag(d.l,!0)},700,this);
g.G(this,this.C)},RHa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promoci\u00f3n");a.element.tabIndex=0;var e=sHa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ca:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",oa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),h.appendChild(f));e&&W1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.hd(f,O1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
oa:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ca:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ca:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",oa:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&W1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&W1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",oa:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ca:["yt-badge","iv-promo-badge-live"],oa:"EN DIRECTO AHORA"})),g.K(a.i,"iv-click-target"),e&&W1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);
p&&a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ca:["iv-promo-expand","ytp-button"]});a.l.title="Expandir";a.context.i.Pa(a.l,"click",function(r){i2(a,5E3,r)});
c.appendChild(a.l);g.Ag(a.l,!1);a.context.i.Pa(a.element,"mouseover",a.PN,a);a.context.i.Pa(a.element,"mouseout",a.ON,a);a.context.i.Pa(a.element,"touchend",function(r){i2(a,5E3,r)});
a.u=a.createElement({D:"button",Ca:["iv-promo-close","ytp-button"]});a.u.title="Cerrar";a.context.i.Pa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.LN:a.KN,a);c.appendChild(a.u);g.yn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},i2=function(a,b,c){c.stopPropagation();
SHa(a);THa(a,b);a.i.focus()},UHa=function(a){a.isCollapsed||a.L||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},SHa=function(a){a.C.stop();
a.isCollapsed&&(g.An(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Ag(a.l,!1),g.Ag(a.u,!0))},THa=function(a,b){a.B||(a.B=g.Im(function(){j2(this);
UHa(this)},b,a))},j2=function(a){a.B&&(g.B.clearTimeout(a.B),a.B=null)},VHa=function(a){this.I=a},DHa=function(a,b,c){b&&(c?k2(a,b.map(function(d){return g.jn(d,c)})):k2(a,b))},k2=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Nq(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},l2=function(a){g.dM.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.J={};this.logger=new VHa(this.player);this.C=new g.TL(this);this.G=this.u=null;this.events=new g.TL(this);this.L=this.i=null;this.X=[];g.G(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.C.N(this.player,"resize",function(d){b.W("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.DL,this);this.subscribe("resize",this.ax,this);this.player.T().V.subscribe("vast_info_card_add",this.BI,this);g.G(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.V({D:"div",Ca:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.l);g.GL(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ca:["ytp-iv-video-content"]});g.G(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.gp()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Ei(this,function(){g.Je(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},WHa=function(a){a=a.createElement({D:"div",
Ca:["annotation","annotation-type-custom"]});g.Ag(a,!1);return a},XHa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
a.l.Vb(b);a.B.Vb(b)},YHa=function(a,b,c){a.V=!0;
a.G=g.wp(b,c)},ZHa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(ZHa(a,e))}return c},bIa=function(a){var b=a.player.getVideoData();
if(b.xa){var c=a.player.T().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.op(h)&&h.responseXML?h.responseXML:null)&&m2(a,h)}};
g.mq()&&(d.onFinish=$Ha(a,d.onFinish));d.postParams={ic_only:"1"};aIa(d,c);a.V=!0;g.wp(b.xa,d)}}},aIa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Rr&&(a.postParams.ic_coll=b.Rr);b.qv&&(a.postParams.ic_xml=b.qv);b.Bu&&(a.postParams.ic_track=b.Bu)},cIa=function(a){var b=new g.V({D:"div"});
g.Ag(b.element,!1);var c=new $1(a.player,b.element,n2(a));g.G(c,b);b.ya(a.l.element);c.Zt();return c},n2=function(a){if(!a.L){var b=new y1(a);
g.G(a,b);var c=new g.a0(a);g.G(a,c);a.L=new QHa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.dd)}return a.L},m2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Fu();if(e){var f=g.Du();f&&g.Yu(g.Qo("use_default_events_client")?void 0:g.Zt,e,f,[g.zu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=ZHa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=N1(f.type,dIa),p=N1(f.style,eIa),r=M1(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=pHa;if(null==u)var x=null;else if(g.Ma(u)){l=[];for(var y=g.q(u),A=y.next();!A.done;A=
y.next()){var E=f(A.value);E&&l.push(E)}x=l}else{var I=f(u);x=I?[I]:[]}e=m&&n?new qHa(m,n,p,x,t):null}else e=null}catch(Ya){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=WHa(f),U=null;switch(l.type){case "branding":if(f.player.T().tb)break;f.l.element.appendChild(H);U=new g2(H,n2(f),l);break;case "promotion":g.GL(f.player,H,4),U=new h2(H,n2(f),l)}U&&U.Zt();if(f=U)g.G(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=cIa(a),g.G(a,a.i));if("card"===e.type){c=
a.i;var N=e&&e.data&&e.data.card_type;f=e.data;if(N)switch(l=f.tracking||{},l={IG:l.impression,click:l.click,close:l.close,AJ:l.teaser_impression,Mx:l.teaser_click},H=f.tracking_params||{},U=null,N){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Nd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Hk:H.card?g.zu(H.card):null,ci:H.teaser?g.zu(H.teaser):null,Zd:H.icon?
g.zu(H.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,LI:f.image_url,title:f.title,metaInfo:f.meta_info,url:P1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};c2(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Nd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Hk:H.card?g.zu(H.card):
null,ci:H.teaser?g.zu(H.teaser):null,Zd:H.icon?g.zu(H.icon):null,xu:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:P1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};c2(c,e);break;case "productListing":f.signin_url&&(U=P1({target:"current",value:f.signin_url}));N=[];for(var fa=f.offers||[],ya=0;ya<fa.length;ya++)N.push(new vHa(g.od(fa[ya].merchant),g.od(fa[ya].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Nd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Hk:H.card?g.zu(H.card):null,ci:H.teaser?g.zu(H.teaser):null,Zd:H.icon?g.zu(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Zu:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:P1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),u6:U,t6:f.signin_title?f.signin_title:void 0,s6:f.signin_message?f.signin_message:void 0,offers:N};c2(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Nd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Hk:H.card?g.zu(H.card):null,ci:H.teaser?g.zu(H.teaser):
null,Zd:H.icon?g.zu(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Zu:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:P1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};c2(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,Nd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Hk:H.card?g.zu(H.card):null,ci:H.teaser?g.zu(H.teaser):null,Zd:H.icon?g.zu(H.icon):null,xu:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:P1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},c2(c,e)}}else zHa(a.i,e);c=!0}}c&&(q1(a.player),a.ax())},fIa=function(a,b){var c=!1;
a.i||(a.i=cIa(a),g.G(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(AHa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.ew(b.headerText):"",g.Re(c.bb,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.xa=b.trackingParams?g.zu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.zu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Zd=b.icon.infoCardIconRenderer.trackingParams?
g.zu(b.icon.infoCardIconRenderer.trackingParams):null,q1(a.player),a.ax())},gIa=function(a,b,c,d,e){if(!a.player.T().tb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new mHa("openUrl","click",new kHa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.ew(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.ew(b.subscriberCountText))):(b.subscriberCountText&&(e=g.ew(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.ew(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.ew(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.ew(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new qHa(c,"branding","branding",f,d);l=WHa(a);a.l.element.appendChild(l);f=new g2(l,n2(a),f);f.Zt();g.G(f,f);a.J[c]=f}},$Ha=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||a.X.push(g.jq(function(){b.apply(null,g.ma(d))}))}},hIa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.zL.prototype.Kq=g.ca(17,function(a,b){var c=g.uM(this.rb());c&&c.Kq(a,b)});
var s1={},t1=null;g.Ta(v1,g.Cn);g.k=v1.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.gb)this.progress=0,this.coords=this.i;else if(this.wc())return!1;u1(this);this.startTime=a=g.Sa();-1==this.gb&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Yw();this.Hh("play");-1==this.gb&&this.Hh("resume");this.gb=1;var b=g.Pa(this);b in s1||(s1[b]=this);VGa();WGa(this,a);return!0};
g.k.stop=function(a){u1(this);this.gb=0;a&&(this.progress=1);XGa(this,this.progress);this.Hh("stop");this.Dt()};
g.k.pause=function(){this.wc()&&(u1(this),this.gb=-1,this.Hh("pause"))};
g.k.ra=function(){0==this.gb||this.stop(!1);this.Hh("destroy");v1.Od.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.Oy=function(){this.Hh("animate")};
g.k.Hh=function(a){this.dispatchEvent(new YGa(a,this))};
g.Ta(YGa,g.yl);g.Ta(w1,v1);w1.prototype.u=g.Ja;w1.prototype.Oy=function(){this.u();w1.Od.Oy.call(this)};
w1.prototype.Dt=function(){this.u();w1.Od.Dt.call(this)};
w1.prototype.Yw=function(){this.u();w1.Od.Yw.call(this)};
g.Ta(x1,w1);x1.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(y1,g.F);y1.prototype.Pa=function(a,b,c,d){c=(0,g.C)(c,d||this.i);a=g.Vp(a,b,c);this.l.push(a);return a};
y1.prototype.mB=function(a,b,c,d){c=(0,g.C)(c,d||this.i);a=g.dq(a,b,c);this.l.push(a);return a};
y1.prototype.jc=function(a){g.Wp(a);g.lb(this.l,a)};
y1.prototype.ra=function(){g.Wp(this.l);this.l.length=0;g.F.prototype.ra.call(this)};g.v(C1,g.dM);g.k=C1.prototype;g.k.load=function(){g.dM.prototype.load.call(this);if(!D1(this)){var a=g.fja(this.player.getVideoData());a?(a=B1(a,$Ga(this)),E1(this,a,!1)):aHa(this)}};
g.k.unload=function(){E1(this,null);this.u&&(this.u.abort(),this.u=null);g.dM.prototype.unload.call(this)};
g.k.Oe=function(a,b){return D1(this)?"loadCustomEndscreenRenderer"===a?(a=B1(b,"new"),E1(this,a),!0):null:null};
g.k.getOptions=function(){return D1(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.sb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<iIa.length;f++){var h=Math.abs(b.width-iIa[f]);if(-1===e||d>=h)e=f,d=h}d=jIa[e];this.l&&g.jg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.yg(e.element,Math.round(h.width*a.width),f);g.rg(e.element,m,n);g.An(e.element,kIa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.An(e.element,jIa);g.K(e.element,d);(e=g.re(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.jg(e,"height",f+"px")}}}}};
g.k.zd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())L1(this,this.endscreen.impressionUrls),(a=g.Fu())&&this.endscreen.visualElement&&g.Zu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");L1(this,c.impressionUrls);(b=g.Fu())&&g.Zu(b,c.visualElement,void 0);this.player.T().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.We=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.zn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.zn(b,"ytp-ce-shown");this.player.T().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.WR=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.An(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var iIa=[346,426,470,506,570,640,853,1280,1920],jIa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),kIa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var lHa={RW:"current",o1:"new"};var nHa={CLOSE:"close",H1:"openUrl",AM:"subscribe"},oHa={JU:"click",CLOSE:"close",eY:"hidden",T2:"rollOut",U2:"rollOver",J3:"shown"};var eIa={dU:"anchored",kK:"branding",CHANNEL:"channel",PW:"cta",hY:"highlightText",eZ:"label",PLAYLIST:"playlist",r2:"popup",R3:"speech",AM:"subscribe",j4:"title",VIDEO:"video",r5:"website"},dIa={kK:"branding",wU:"card",dX:"drawer",gY:"highlight",E_:"marker",z2:"promotion",TEXT:"text",x5:"widget"};g.v(V1,g.F);g.k=V1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Vv(a,b,{id:c});a.namespace="annotations_module";d&&this.Ga.set(a,d);e&&this.Na.set(a,e);this.context.I.Dd([a])};
g.k.Zt=function(){this.context.l.subscribe("resize",this.ev,this)};
g.k.Py=function(a,b,c,d,e,f){if(this.Wa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Je(this.element)};
g.k.ev=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=O1(a);if(f){var h=xHa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.cp(f||"");m&&n&&(n.v||n.list)?e.context.I.dj(n.v,b,n.list,!1):g.AI(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);k2(this.context.logger,c,l,d);wHa(f)||(c=g.Fu(),d=b.itct,c&&d&&g.hv(c,g.zu(d)))}};
g.k.ra=function(){this.Ga.clear();this.Na.clear();g.F.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.G(this,a);return a.element};g.v($1,V1);g.k=$1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.zg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ev=function(){var a=this.isAvailable();g.Ag(this.element,a);g.L(this.context.I.getRootNode(),g.wS.IV_DRAWER_ENABLED,a);q1(this.I)};
g.k.destroy=function(){this.I.Kq(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.Vq(this.X);g.Wp(this.ma);this.Da&&this.Da.dispose();this.C&&this.C.dispose();V1.prototype.destroy.call(this)};
g.k.YM=function(){if(this.u){k2(this.context.logger,e2(this).tracking.close);var a=g.Fu();a&&this.J&&g.hv(a,this.J);Z1(this)}};
g.k.kN=function(){g.L(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.AO=function(){var a=g.Fu(),b=e2(this);b=b?b.Zd:this.Zd;a&&b&&g.fv(a,[b])};
g.k.zO=function(){var a=g.Fu(),b=e2(this);b=b?b.Zd:this.Zd;a&&b&&g.gv(a,[b])};
g.k.CL=function(){var a=e2(this);k2(this.context.logger,a.tracking.AJ);var b=g.Fu();b&&a&&g.fv(b,[a.ci,a.Zd])};
g.k.CO=function(){var a=g.Fu(),b=e2(this);a&&b&&g.gv(a,[b.ci])};
g.k.BL=function(a){var b=e2(this),c=g.Fu();this.i?a?(a=this.context.logger,k2(a,b.tracking.Mx),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ci&&g.hv(c,b.ci)):(a=this.context.logger,k2(a,b.tracking.Mx),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Zd&&g.hv(c,b.Zd)):(a=this.context.logger,k2(a,b.tracking.Mx),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Zd&&g.hv(c,this.Zd))};g.v(f2,V1);f2.prototype.Zt=function(){V1.prototype.Zt.call(this);LHa(this)};
f2.prototype.show=function(){V1.prototype.show.call(this);var a=g.Fu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.fv(a,[g.zu(b.itct)])};
f2.prototype.hide=function(){V1.prototype.hide.call(this);var a=g.Fu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.gv(a,[g.zu(b.itct)])};g.v(g2,f2);
g2.prototype.show=function(){if(!this.isActive){f2.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ca:["branding-img","iv-click-target"],U:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ag(this.l,!1);var b=this.createElement({D:"div",Ca:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=sHa(this.annotation))&&W1(this,this.l,b,this.annotation.id,
a.session_data);PHa(this,a);this.J=!0}g.Ag(this.element,!0);this.isActive=!0;this.l&&MHa(this,this.l)}};
g2.prototype.hide=function(){this.isActive&&(f2.prototype.hide.call(this),g.Ag(this.element,!1),this.isActive=!1)};
g2.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);f2.prototype.destroy.call(this)};g.v(h2,f2);g.k=h2.prototype;g.k.show=function(){this.isActive||(f2.prototype.show.call(this),this.V||(RHa(this),this.V=!0),g.Ag(this.element,!0),g.Im(function(){g.zn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,j2(this),SHa(this),THa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.Py=function(a,b,c,d,e,f){return this.isCollapsed?!1:f2.prototype.Py.call(this,a,b,c,d,e,f)};
g.k.PN=function(a){this.L=!0;i2(this,500,a)};
g.k.ON=function(){this.L=!1;UHa(this)};
g.k.KN=function(a){a.stopPropagation();this.hide()};
g.k.LN=function(a){a.stopPropagation();j2(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();f2.prototype.destroy.call(this)};g.v(l2,g.dM);g.k=l2.prototype;g.k.Oe=function(a,b){if(!hIa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.$_(b))&&m2(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(CHa(this.i,b),q1(this.player)),!0}return null};
g.k.getOptions=function(){return hIa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.gp=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.TE||a.V.get(b.videoId)||g.mG(b)||g.nG(b)?!0:!1};
g.k.ax=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.yg(this.B.element,a.width,a.height);g.rg(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Ai();a=this.i;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.k.DL=function(a){XHa(this,a.state);g.T(a.state,2)&&(this.Zg()&&this.Fj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Kq(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.op(h)&&h.responseXML?h.responseXML:null)&&(m2(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.dM.prototype.load.call(this);XHa(this,this.player.ub());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.mq()&&(a=$Ha(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().V.get(d);f&&aIa(e,f);f=f&&(f.qv||f.Rr);if(!c.Bk||f)c.xa?YHa(this,c.xa,e):(this.u=function(){b.kb(e)},this.player.addEventListener("videodatachange",this.u));
g.GL(this.player,this.B.element,4);this.ax();(f=g.mG(c))&&fIa(this,f);(f=g.nG(c))&&f.featuredChannel&&gIa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.kb=function(a){var b=this.player.getVideoData();b.xa&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),YHa(this,b.xa,a))};
g.k.unload=function(){this.player.Ye("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,q1(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.dM.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.BI=function(a){a===this.player.getVideoData().videoId&&(this.loaded?bIa(this):this.load())};
g.k.Zg=function(){return!!this.i&&this.i.isAvailable()};
g.k.Fj=function(){this.Zg();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Zg();this.i&&(a?c?Y1(this.i,c,b):Y1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):Z1(this.i))};
g.k.Kq=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.T().V.unsubscribe("vast_info_card_add",this.BI,this);g.zn(this.player.getRootNode(),g.wS.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.nq(a[b]);this.X.length=0;g.dM.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.G(this,a);return a.element};g.oM.annotations_module=l2;g.oM.creatorendscreen=C1;})(_yt_player);
