(function(g){var window=this;'use strict';var r2=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},s2=function(a){return g.ZD(a)&&a.Z("web_player_i_see_captions_3")},lIa=function(a,b){return g.D(this,function d(){var e,f;
return g.z(d,function(h){if(1==h.i)return e=a+"|"+b,g.w(h,(0,g.BE)(),2);f=h.l;return h.return(f.get("captions",e))})})},mIa=function(a,b){var c=new g.GE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},nIa=function(a,b,c){lIa(a,b).then(function(d){d&&c(d.trackData,new g.GE(d.metadata))})},t2=function(){this.segments=[]},oIa=function(a,b){var c=g.vb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.kb(a.segments,c),g.kb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.sb(a.segments,c,0,b),g.sb(a.segments,c+1,0,b)))},u2=function(a,b,c,d,e,f){g.F.call(this);
this.policy=a;this.player=b;this.X=c;this.G=d;this.C=e;this.V=f;this.J=this.player.T();this.B=new t2;this.l=this.u=this.i=null;this.L=new g.J(this.mH,1E3,this);this.events=new g.TL(this);g.G(this,this.L);g.G(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.MD);this.MD();this.mH()},pIa=function(a,b){var c=g.Hz(g.hA(b,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.Bp(c,d,3,100).then(function(e){a:{var f=e.xhr;a.Ha();if(a.u){var h=!(a.C?f.response:f.responseText)||400<=f.status;if(e=g.QB(f)){f=g.hA(a.u,{});h=a.u;g.Oz(h.l,f,e);h.requestId=f.get("req_id");pIa(a,a.u);break a}h||null==a.G||(e=a.u.i[0],a.C?a.G(f.response,1E3*(e.startTime+a.player.Mc())):a.G(f.responseText,1E3*(e.startTime+a.player.Mc())))}a.u=null;a.l=null}});
a.u=b;oIa(a.B,a.u.i[0].Ja)},v2=function(a,b){g.gM.call(this,b.T());
this.i=a;this.I=b;this.u=null;this.C=!1;this.G=g.bE(this.I.T())&&!this.i.isManifestless},rIa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.iM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.vGa.get(e);null==n&&(n=qIa[e]||qIa[e.replace(/-/g,"_")],g.vGa.set(e,n));h=n||h}c.push(new g.GE({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},sIa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},tIa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.iM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},w2=function(a){if(!uIa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(vIa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},x2=function(a,b,c,d,e,f){var h={};
g.Ra(h,b);g.Ra(h,a.params);g.Ra(h,c);var l={};g.Ra(l,b.Zc);a.params.Zc&&g.Ra(l,a.params.Zc);g.Ra(l,c.Zc);h.Zc=l;g.V.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.Df?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ma=!1;this.l=a;this.xa=this.va=null;this.playerWidth=e;this.playerHeight=f;this.G=null;this.maxWidth=.96*e;this.maxHeight=.96*f;this.i=h;this.qb=c;
this.Aa=b;this.B=this.Ba("captions-text");this.bb=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Fa=d/360*16;this.type=0;this.Na=this.Fa*wIa(l);a=new g.ou(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.GL,this);a.subscribe("dragmove",this.FL,this);a.subscribe("dragend",this.EL,this);this.Wa=this.Qa=0;b="";this.i.windowOpacity&&(a=w2(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+
")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":xIa[this.i.textAlign]};this.bb&&(a["border-radius"]=b?this.Na/8+"px":"");if(this.u=2===this.l.params.Df||3===this.l.params.Df)b=this.element,c="vertical-rl",1===this.i.OC&&(c="vertical-lr"),g.ye&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.jg(b,"-o-writing-mode",c),g.jg(b,"-webkit-writing-mode",c),g.jg(b,"writing-mode",c),g.jg(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3===this.l.params.Df&&(g.jg(b,"text-orientation",
""),g.jg(b,"transform","rotate(180deg)"));g.jg(this.element,a);switch(this.i.Fh){case 0:case 1:case 2:g.K(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},wIa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},yIa=function(a,b){var c={},d=b.background?b.background:a.i.Zc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Zc.backgroundOpacity;d=w2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.bb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Na/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Fa*wIa(b)+"px";d=1;e=b.color||a.i.Zc.color;if(b.color||null!=b.textOpacity)e=w2(e),d=null==b.textOpacity?a.i.Zc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Lz&&(h=e=b.Lz);var l=a.Fa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.zq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Zc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Di&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.hO&&(c.visibility="hidden");1===b.GG&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.fE||g.Is,3===a.l.params.Df?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Wi||2===b.Wi||3===b.Wi||4===b.Wi||5===b.Wi)if(g.fE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Wi){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},zIa=function(a){a.G=g.Fe("SPAN");
g.jg(a.G,{display:"block"});g.K(a.G,"caption-visual-line");a.B.appendChild(a.G)},AIa=function(a,b){var c=g.Fe("SPAN");
g.jg(c,{display:"inline-block","white-space":"pre-wrap"});g.jg(c,yIa(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.jg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.jg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},BIa=function(a,b,c){a.ma=a.ma||!!c;
var d={};g.Ra(d,a.i.Zc);g.Ra(d,c||b.i);g.Ra(d,a.qb.Zc);(c=!a.G)&&zIa(a);for(var e=a.va&&a.xa&&g.Sb(d,a.xa)?a.va:AIa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(zIa(a),e=AIa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ge(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.fE||!g.ng(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.ng(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.Ae?g.jg(e,m,"1em"):g.jg(e,m,"0.5em")))}a.xa=d;a.va=e;a.C.push(b)},y2=function(a,b,c){g.gM.call(this,a);
this.videoData=b;this.audioTrack=c;this.B=b.oz},z2=function(a,b,c,d,e,f,h){x2.call(this,a,b,c,d,e,f,h);
this.type=1},A2=function(a,b,c,d,e,f,h){x2.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.X=this.L=this.Da=0;this.Y=NaN;this.Ya=0;this.eb=null;this.Ga=new g.J(this.fR,433,this);g.K(this.element,"ytp-caption-window-rollup");g.G(this,this.Ga);g.jg(this.element,"overflow","hidden")},CIa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.OC&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},DIa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.rl,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Pl)?(e=g.Fe("SPAN"),g.Re(e,"\u2013".repeat(d)),g.jg(e,yIa(a,a.i.Zc)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.X=c.call(b,a.Y,a.Ya,(a.u?d.offsetHeight:d.offsetWidth)+1)},EIa=function(a,b){DIa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.Da){var d=0<c&&0===a.Da;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.pn(a.Ga));g.jg(a.B,"transform",CIa(a,c));a.Da=c}DIa(a)},B2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Vv.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},C2=function(a,b,c,d,e){g.Vv.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},FIa=function(a){var b="_"+D2++;
return new C2(0,0x8000000000000,0,b,a)},HIa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Md){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=GIa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new B2(a,b,e,c,l,d,m)}switch(m.Md){case 9:case 10:m.Wi=1;break;case 11:m.Wi=2;break;case 12:m.Wi=3;break;case 13:m.Wi=4;break;case 14:m.Wi=5}return new B2(a,b,e,c,l.textContent||"",d,m)},GIa=function(a,b,c,d,e){var f=g.zq(),h=
f?g.Fe("DIV"):g.Fe("RUBY"),l=g.Fe("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Fe("DIV"):g.Fe("RP");a.textContent=b;h.appendChild(a);b=f?g.Fe("DIV"):g.Fe("RT");b.textContent=c;h.appendChild(b);c=e.Md;if(10===c||11===c||12===c||13===c||14===c)if(g.jg(b,"text-emphasis-style","filled circle"),g.jg(b,"text-emphasis-color","currentcolor"),g.jg(b,"webkit-text-emphasis","filled circle"),11===e.Md||13===e.Md)g.jg(b,"webkit-text-emphasis-position","under left"),g.jg(b,"text-emphasis-position","under left");c=!0;if(4===e.Md||7===e.Md||12===e.Md||
14===e.Md)g.jg(h,"ruby-position","over"),g.jg(h,"-webkit-ruby-position","before");else if(5===e.Md||6===e.Md||11===e.Md||13===e.Md)g.jg(h,"ruby-position","under"),g.jg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Fe("DIV"):g.Fe("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.jg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.jg(f,"display","none"),f=f.nextElementSibling,g.jg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.jg(h.lastElementChild,"display","none"),d?(g.jg(h,"padding-top","0.6em"),g.jg(f,"top","0")):(g.jg(h,"padding-bottom","0.6em"),g.jg(f,"bottom","0")));return h},E2=function(){g.F.apply(this,arguments)},F2=function(a){E2.call(this);
this.C=a;this.B={};this.V={};this.X={};this.G="_"+D2++;this.L={};this.u=this.i=null;this.J=!0},G2=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},H2=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},I2=function(a,b){a=G2(a,b);
return void 0!==a?a:null},K2=function(a,b){a=a.getAttribute(b);
if(null!=a)return J2.test(a),a},IIa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.X[d]:a.C);a=I2(b,"mh");null!=a&&(c.Cq=a);a=I2(b,"ju");null!=a&&(c.textAlign=a);a=I2(b,"pd");null!=a&&(c.Df=a);a=I2(b,"sd");null!=a&&(c.OC=a);a=K2(b,"wfc");null!=a&&(c.windowColor=a);b=G2(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},JIa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.V[d]);a=I2(b,"ap");null!=a&&(c.Fh=a);a=G2(b,"cc");null!=a&&(c.Pl=a);a=G2(b,"ah");null!=a&&(c.Kg=a);a=G2(b,"rc");null!=a&&(c.rl=a);b=G2(b,"av");null!=b&&(c.Xi=b);return c},KIa=function(a,b,c,d){var e={};
g.Ra(e,JIa(a,b));g.Ra(e,IIa(a,b));d?g.Sb(e,a.C)?(d=a.G,e=a.C):d="_"+D2++:d=b.getAttribute("id")||"_"+D2++;a=G2(b,"t")+c;b=G2(b,"d")||0x8000000000000;if(2===e.Df||3===e.Df)c=e.rl,e.rl=e.Pl,e.Pl=c;return new C2(a,b,0,d,e)},L2=function(a){E2.call(this);
this.G=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},M2=function(a){a=g.de(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},LIa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.rl=a);b=b.ccColCount;void 0!==b&&(f.Pl=b);if(2===f.Df||3===f.Df)b=f.rl,f.rl=f.Pl,f.Pl=b;return new C2(c,d,0,e,f)},O2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new N2(this);this.C=new N2(this);this.i=[];this.clear()},NIa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{In:a,
Kl:b,result:0};a=MIa[a];b=MIa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Kl===d;if(d)return{In:a,Kl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{In:a,Kl:b,result:2};return{In:a,Kl:b,result:3}},PIa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,OIa(a.B,b,c,d))},QIa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?PIa(a,d.sF,d.tF,b):1===d.type&&a.l&496&&OIa(a.C,d.sF,d.tF,b);a.i.length=0},P2=function(){this.type=0},Q2=function(){this.state=this.Kl=this.In=0},RIa=function(){this.timestamp=this.i=0},R2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new P2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new RIa}},S2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},WIa=function(a,b){switch(a){case 0:return SIa[(b&127)-32];
case 1:return TIa[b&15];case 2:return UIa[b&31];case 3:return VIa[b&31]}return 0},T2=function(a){return a.u[a.row][a.l]},U2=function(a,b,c){2<=b&&1<a.l&&(--a.l,T2(a).i=0);
var d=T2(a);d.timestamp=a.C.time+0;d.i=WIa(b,c);32>a.l&&a.l++},XIa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},V2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},W2=function(a){a.row=0<a.i?a.i:1;
a.l=1;V2(a,0,15)},X2=function(a){this.u=a;
this.C=0;this.style=new P2;this.G=new R2(this.u);this.J=new R2(this.u);this.text=new R2(this.u);this.l=this.G;this.B=this.J;this.i=this.l},Y2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(S2(d,c),W2(a.l),W2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(S2(d,c),V2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},YIa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},ZIa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},N2=function(a){this.i=a;
this.C=0;this.u=new X2(this.i);this.G=new X2(this.i);this.l=new Q2;this.B=this.u},OIa=function(a,b,c,d){a.l.update();
b=NIa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.In;c=b.Kl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&U2(a,0,b),c&96&&U2(a,0,c),0!==b&&0!==c&&3===a.style.type&&S2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.In=e,b.Kl=c,b.state=2,b=e&8?a.G:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;XIa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));V2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:U2(b.i,0,32);break a;case 48:57===c?(d=b.i,T2(d).i=0,32>d.l&&d.l++):U2(b.i,1,c&15)}break;case 2:c&32&&U2(b.i,2,c&31);break;case 3:c&32&&U2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:YIa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,T2(d).i=0);break;case 36:d=b.i;b=T2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:Y2(b,2,d);break;case 38:Y2(b,3,d);break;case 39:Y2(b,4,d);break;case 40:U2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);W2(d);ZIa(b);break;case 43:ZIa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:S2(a,d)}V2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;S2(a,d);XIa(a,b,b+1,a.i-1);V2(a,a.row,1)}break;case 46:V2(b.B,0,15);break;case 47:S2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,YIa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},$Ia=function(){},Z2=function(a,b,c){this.trackData=a;
this.G=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.trackData);this.l=[]},$2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},a3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},b3=function(a,b){E2.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new O2;this.i.l=1<<this.track},c3=function(a){if("string"===typeof a)return!1;
a=new Z2(a,8,0);return aJa(a)},aJa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==a3(a))return!1;
a.version=$2(a);if(1<a.version)return!1;$2(a);$2(a);$2(a);return!0},d3=function(){E2.call(this)},bJa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Di=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new B2(b,c,d,e.id,p.nodeValue,f||0<n,g.Pb(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Ra(r,l);bJa(a,b,c,d,e,!0,p,r,m)}}},e3=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},cJa=function(a,b,c,d){d=Object.assign({Cq:0},d);
return new C2(a,b,c,"_"+D2++,d)},f3=function(a){g.F.call(this);
this.l=a;this.i=null},dJa=function(a,b){if("string"===typeof b||c3(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.$y(c,0,1835295092);if(!c||!c.size)return"";a=a.l.Z("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.Ze(new Uint8Array(a))},fJa=function(a){var b={};
if(a=g.JE(a))b.lang=a,eJa.test(a)&&(b.Df=1);return b},i3=function(a){g.dM.call(this,a);
var b=this;this.I=a;this.i=this.I.T();this.videoData=this.I.getVideoData();this.bb=this.I.Za();this.B={Zc:{}};this.C={Zc:{}};this.Y=[];this.V={};this.Da={};this.X=!1;this.qb=g.uG(this.videoData);this.Wa=g.Uoa(this.videoData,this.I);this.eb=!!this.videoData.captionTracks.length;this.tb=!!this.videoData.Cc;this.Xa="3"===this.i.controlsType;this.u=this.J=this.L=this.Fa=this.Qa=null;this.Ga=new f3(this.i);this.l=null;this.xa=new g.TL(this);this.Na=new g.V({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.qo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Sn(d));this.storage=c;c=a.ud();d=!(null===c||void 0===c||!c.uu());this.Ya=!(null===c||void 0===c||!c.vu());this.G=this.Xa&&d&&!this.Wa;this.va=!this.G&&this.Xa&&this.Ya&&this.Wa;g.G(this,this.Ga);this.G?this.Aa=this.ma=null:(this.ma=new g.ln(this.fD,void 0,this),g.G(this,this.ma),this.Aa=new g.J(this.sS,2E3,this),g.G(this,this.Aa));g.G(this,this.xa);this.i.Z("caption_window_container_killswitch")||g.GL(this.player,this.Na.element,
4);g.G(this,this.Na);this.G||this.xa.N(a,"resize",this.hD);this.xa.N(a,"onPlaybackAudioChange",this.tP);this.xa.N(a,g.Yv("captions"),function(e){b.zd(e)});
this.xa.N(a,g.Zv("captions"),function(e){b.We(e)});
g3(this,h3(this,"display-settings")||{})},gJa=function(a){if(1===a.i.Ga||1===a.videoData.Ap||"alwayson"===g.eG(a.videoData,"yt:cc"))return!0;
if(2===a.i.Ga){var b;g.eE(a.i)?b=(0,g.cM)():b=h3(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().l;b=r2(a.player.getAudioTrack(),s2(a.i));var d=g.eG(a.videoData,"yt:cc");if(void 0===j3(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.eG(a.videoData,"yt:cc")},k3=function(a,b){if(a.l&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.l},j3=function(a){var b=void 0,c=g.wr(g.ur.getInstance(),65);
if(g.eE(a.i)&&null!=c){if(null!=(0,g.cM)())return!1;b=!c}return b},hJa=function(a){var b;
a.qb?b=new y2(a.i,a.videoData,a.player.getAudioTrack(),a.player):a.Wa?b=new v2(a.videoData.i,a.player):a.eb?b=new g.hM(a.i,a.videoData,a.player.getAudioTrack()):b=new g.jM(a.videoData.Cc,a.videoData.videoId,g.ija(a.videoData),a.videoData.Vh,a.i);return b},m3=function(a,b){if(a.u){if(a.J&&a.J.B)return a.J.B;
b||(b=a.tb?!1:a.eb?!1:!0);b=g.eM(a.u.l,b);for(var c=[a.videoData.captionsLanguagePreference,a.i.captionsLanguagePreference,g.eG(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.JE(b[e])===c[d])return b[e];return a.J&&a.J.u?a.J.u:(c=b.find(function(f){return f.isDefault}))?c:b[0]||l3(a)}return null},l3=function(a){return a.J&&a.J.i},n3=function(a){var b=l3(a);
return!!b&&a.l===b},iJa=function(a,b){var c=a.I.ud().ue().textTracks;
a=a.l.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},p3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.X=c,a.X&&(g.eE(a.i)?(0,g.J0)(!!b):o3(a,"module-enabled",!!b)));a.l=b;k3(a)&&(a.l=l3(a));a.load()},jJa=function(a,b){a.i.Z("caption_window_container_killswitch")?g.GL(a.player,b,4):a.Na.element.appendChild(b)},kJa=function(a,b){var c=a.bb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.l?g.JE(a.l):null;d&&eJa.test(d)&&(b.params.Df=1);d=a.bb.getPlayerSize();switch(null!=b.params.Cq?b.params.Cq:1<b.i.length?1:0){case 1:return new z2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);case 2:return new A2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);default:return new x2(b,a.B,a.C,c,d.width,d.height,a.i.experiments)}},g3=function(a,b,c){c=void 0===c?!1:c;
var d=q3.Zc;a.B={};g.Ra(a.B,q3);a.B.Zc={};g.Ra(a.B.Zc,d);a.C={Zc:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;J2.test(f);e.Zc.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;J2.test(f);e.Zc.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||q3.windowColor;J2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Zc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Zc.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Di?3:d.bold?1:d.Di?2:0);f=f.Zc;switch(e){case 1:f.bold=!0;delete f.Di;break;case 2:delete f.bold;f.Di=!0;break;case 3:f.bold=!0;f.Di=!0;break;default:delete f.bold,delete f.Di}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Zc.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=q3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Zc.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Zc.fontFamily=f;a.loaded&&a.hD();c&&o3(a,"display-settings",b)},mJa=function(a,b){b&&!a.L?(b=FIa({Df:0,
lang:"es"}),a.L=[b,new B2(b.start,b.end-b.start,0,b.id,"Los subt\u00edtulos tendr\u00e1n este aspecto")],a.player.Dd(a.L)):!b&&a.L&&(lJa(a,a.L),a.L=null)},lJa=function(a,b){a.player.Nf(b);
g.Ab(b,function(c){g.lb(this.Y,c)},a);
g.mn(a.ma)},h3=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},o3=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.SR.prototype.Bs=g.ca(31,function(a){var b=2;this.Fa.has(a)?b=0:g.Sta(this,a)&&(b=1);return b});
g.iU.prototype.Bs=g.ca(30,function(a){return this.i.Bs(a)});
g.xM.prototype.Sr=g.ca(29,function(){this.ea();for(var a=g.re(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Je(a[b])});
g.DR.prototype.Sr=g.ca(28,function(){this.i.Sr()});
g.xM.prototype.vu=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.DR.prototype.vu=g.ca(26,function(){return this.i.vu()});
g.xM.prototype.uu=g.ca(25,function(){return!!this.i.textTracks});
g.DR.prototype.uu=g.ca(24,function(){return this.i.uu()});
g.xM.prototype.Jr=g.ca(23,function(a){this.ea();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.DR.prototype.Jr=g.ca(22,function(a){this.i.Jr(a)});
g.gM.prototype.cC=g.ca(21,function(){return!1});
g.gM.prototype.Am=g.ca(20,function(){});
g.hM.prototype.Am=g.ca(19,function(a,b,c){var d=this;this.Ha();b=this.qo(a,b);this.zl();this.i=g.wp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.jM.prototype.Am=g.ca(18,function(a,b,c){var d=this;this.Ha();b=this.qo(a,b);this.zl();this.i=g.wp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.UT.prototype.Ns=g.ca(6,function(){return this.X});
g.tW.prototype.Ns=g.ca(5,function(){var a;return(null===(a=g.W(this))||void 0===a?void 0:a.Hs())||null});
g.zL.prototype.Hs=g.ca(4,function(){return this.app.Ns()});
g.TV.prototype.Hs=g.ca(3,function(){var a;return(null===(a=this.l)||void 0===a?void 0:a.Ns())||null});
var eJa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,qIa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",
as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",
bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",
cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",
en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",
fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",
hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",
kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",
ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",
mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",
nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",
rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",
sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",
tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",
xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
t2.prototype.contains=function(a){a=g.vb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
t2.prototype.length=function(){return this.segments.length/2};
g.v(u2,g.F);g.k=u2.prototype;g.k.ra=function(){g.F.prototype.ra.call(this);this.l&&this.l.cancel()};
g.k.MD=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Mc();var b=this.i;this.i=g.bb(this.X.hm(a).i);b!==this.i&&this.V&&this.V()};
g.k.reset=function(){this.B=new t2;this.l&&(this.l.cancel(),this.l=null)};
g.k.mH=function(){var a;this.Ha();var b;if(b=null!=this.i)b=this.i,b=b.i.Dl(b);if(b&&!this.l&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.lr(b);if(this.J.Z("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Hs();if(c){var d=b.i[0].Ja,e=c.Qv(b.i[0].C,d,b.i[0].i.info.id,!0);if(e)if(c=c.Bs(d),0===c)b.B=e;else if(2===c)return}}b.i[0].duration?(this.B.contains(b.i[0].Ja)||pIa(this,b),this.i=g.bb(b.i)):
!g.R(this.J.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.Mc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime())}this.L.start()};
g.v(v2,g.gM);g.k=v2.prototype;g.k.Am=function(a,b,c){var d=this;this.zl();b=sIa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?tIa(this,b,"386"):tIa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber()));this.u=new u2(new g.Soa,this.I,b,function(f,h){c(f,a,h,e)},this.G||g.MA(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.cC=function(){var a=this.C;this.C=!1;return a};
g.k.yq=function(a){var b=this.G?[new g.GE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.GE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?rIa(this,"386"):rIa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.fM(this.l,c.value);a()};
g.k.zl=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.qo=function(){return""};
var J2=/^#(?:[0-9a-f]{3}){1,2}$/i,vIa=/#(.)(.)(.)/,uIa=/^#(?:[0-9a-f]{3}){1,2}$/i;var xIa=["left","right","center","justify"];g.v(x2,g.V);g.k=x2.prototype;g.k.GL=function(a,b){var c=g.xg(this.element,this.element.parentElement);this.Qa=a-c.x;this.Wa=b-c.y;g.K(this.element,"ytp-dragging")};
g.k.FL=function(a,b){var c=g.zg(this.element);a=a-this.Qa-.02*this.playerWidth;var d=b-this.Wa-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.de(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.de(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.de(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.de(c,0,1);this.l.params.Fh=b;this.l.params.Xi=c;this.l.params.Kg=a;this.i.Fh=b;this.i.Xi=c;this.i.Kg=a;this.Aa.Fh=b;this.Aa.Xi=c;this.Aa.Kg=a;this.fJ()};
g.k.EL=function(){g.zn(this.element,"ytp-dragging")};
g.k.fJ=function(){this.Nq(this.C)};
g.k.Xb=function(){return this.type};
g.k.Nq=function(a){var b=Math.min(this.kG(),this.maxWidth),c=this.jG(),d="";3===this.l.params.Df&&(d="rotate(180deg)");g.jg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.zz(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Kg+2;d=this.i.Fh;switch(d){case 0:case 3:case 6:(b=this.i.Zc.fontSizeIncrement)&&0<b&&2!==this.i.Df&&3!==
this.i.Df&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Xi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.jg(this.element,
a)};
g.k.zz=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ma||this.C.length>b)b=0,this.ma=!1,this.C=[],this.G=this.xa=this.va=null,g.He(this.B);for(;b<a.length;b++)BIa(this,a[b])};
g.k.kG=function(){return 0};
g.k.jG=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.v(y2,g.gM);y2.prototype.Am=function(a,b,c){nIa(this.videoData.videoId,a.vssId,c)};
y2.prototype.yq=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.fM(this.l,c.value);a()};g.v(z2,x2);z2.prototype.zz=function(a){var b=this.l.i;x2.prototype.zz.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Ra(d,c.i);g.Ra(d,nJa);var e=c.i;var f=d}BIa(this,c,d)}};
var nJa={hO:!0};g.v(A2,x2);g.k=A2.prototype;g.k.fJ=function(){g.qn(this.Ga)};
g.k.fR=function(){g.zn(this.element,"ytp-rollup-mode");this.Nq(this.eb,!0)};
g.k.jG=function(){return this.u?this.X:this.L};
g.k.kG=function(){return this.u?this.L:this.X};
g.k.Nq=function(a,b){this.eb=a;if(this.l.params.rl){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Ya=this.X;this.L=this.X=0;x2.prototype.Nq.call(this,a);EIa(this,b)}x2.prototype.Nq.call(this,a)};g.v(B2,g.Vv);B2.prototype.toString=function(){return g.Vv.prototype.toString.call(this)};g.v(C2,g.Vv);C2.prototype.toString=function(){return g.Vv.prototype.toString.call(this)};
var D2=0;g.v(E2,g.F);E2.prototype.l=function(){return[]};
E2.prototype.reset=function(){};g.v(F2,E2);F2.prototype.reset=function(){this.L={};this.u=this.i=null;this.J=!0};
F2.prototype.l=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.B,h={},l=a.getAttribute("p");l&&g.Ra(h,this.B[l]);l=H2(a,"b");null!=l&&(h.bold=
l);l=H2(a,"i");null!=l&&(h.Di=l);l=H2(a,"u");null!=l&&(h.underline=l);l=I2(a,"et");null!=l&&(h.charEdgeStyle=l);l=I2(a,"of");null!=l&&(h.offset=l);l=K2(a,"bc");null!=l&&(h.background=l);l=K2(a,"ec");null!=l&&(h.Lz=l);l=K2(a,"fc");null!=l&&(h.color=l);l=I2(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=G2(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=G2(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=G2(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=I2(a,"rb");null!=l&&10!==l&&0!==l&&(h.Md=10<l?l-
1:l);a=I2(a,"hg");null!=a&&(h.GG=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.X[c]=IIa(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=JIa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=KIa(this,a,b,!1);(a=this.L[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.L[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;h=!!H2(a,"a");l=(G2(a,
"t")||0)+l;var m=G2(a,"d")||5E3;h||(!this.J&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.B[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var u=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.B[u]:null)&&u.Md&&(1===u.Md?(u=r.slice(t,t+4),4===u.length&&(x=HIa(l,m,
f,h,n,u,this.B),t+=3)):x=HIa(l,m,f,h,n,[y],this.B)),!x){var A=y;x=l;y=m;u=f;var E=h,I=n,H=A.textContent?A.textContent:"",U=A.getAttribute("p");U=U?this.B[U]:null;A=G2(A,"t")||0;x=new B2(x+A,y-A,I,u,H,E,U)}}else x=new B2(l,m,n,f,u.textContent||"",h,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.G&&(this.i=KIa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var oJa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(L2,E2);L2.prototype.reset=function(){this.u.clear()};
L2.prototype.l=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Di=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.Lz=M2(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=M2(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=M2(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Md=10<h?h-1:h,f.Wi=oJa.get(f.Md));e.hgHorizGroup&&(f.GG=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.C.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.Cq=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Df=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.OC=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=M2(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.B.get(h)),void 0!==e.ahHorPos&&
(f.Kg=e.ahHorPos),void 0!==e.apPoint&&(f.Fh=e.apPoint),void 0!==e.avVerPos&&(f.Xi=e.avVerPos),void 0!==e.ccCols&&(f.Pl=e.ccCols),void 0!==e.rcRows&&(f.rl=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=LIa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+D2++,h=LIa(this,l,d,e,f),a.push(h),this.u.set(f,h));0===e&&(e=5E3);h=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.Cq?h.params.Cq:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Md)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var A=p[t+1].pPenId;(A=this.i.get(A))&&A.Md&&2===A.Md?(A=p[t+2].pPenId,A=this.i.get(A),!A||!A.Md||3>A.Md?t=!1:(A=p[t+3].pPenId,t=(A=this.i.get(A))&&
A.Md&&2===A.Md?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;A=p[l+2].utf8;var E=this.i.get(p[l+2].pPenId);u=GIa(u,x,A,t,E);m=new B2(d,e,n,f,u,m,y);l+=3}else m=new B2(d+x,e-x,n,h.id,u,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};O2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
O2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var MIa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];P2.prototype.set=function(a){this.type=a};
P2.prototype.get=function(){return this.type};
Q2.prototype.clear=function(){this.state=0};
Q2.prototype.update=function(){this.state=2===this.state?1:0};
Q2.prototype.isValid=function(){return 0!==this.state};
Q2.prototype.matches=function(a,b){return this.isValid()&&a===this.In&&b===this.Kl};
RIa.prototype.reset=function(){this.timestamp=this.i=0};
R2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
R2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
R2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var SIa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],TIa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],UIa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],VIa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];X2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.G;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.G.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
N2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.G.reset(a,1)};$Ia.prototype.B=function(){};g.v(Z2,$Ia);Z2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+D2++;c=c/1E3-this.G;d=d/1E3-this.G;a=new C2(c,d-c,5,f,{textAlign:0,Fh:0,Kg:2.5*b,Xi:5.33*a});e=new B2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.v(b3,E2);b3.prototype.l=function(a){a=new Z2(a,a.byteLength,this.u);if(aJa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=a3(a)*(1E3/45):1===a.version&&(a.u=4294967296*a3(a)+a3(a)),a.C=$2(a);0<a.C;a.C--){var b=$2(a),c=$2(a),d=$2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,sF:c,tF:d,order:b.i.length}))}QIa(this.i,a);return a.l}return[]};
b3.prototype.reset=function(){this.i.clear()};g.v(d3,E2);
d3.prototype.l=function(a,b){var c=[];a=a.split(pJa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!qJa.test(e)){var h=r3.exec(e);if(h&&4<=h.length){var l=e3(h[1]),m=e3(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,u="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Xi=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.Kg=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.Kg=0;break;case 1:h.Kg=100;break;case 2:h.Kg=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.Fh=r}e=e.substring(r3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=cJa(l,m,5,u),m=new B2(l,m,5,f.id,h,!1,g.Pb(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(rJa),1===r.length?(h=5,u=cJa(l,m,h,u)):(p=h=6,u=Object.assign({Pl:32},u),u=new C2(l,m,p,"_"+D2++,u)),c.push(u),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.$_("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,bJa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=e3(n)+f}r3.lastIndex=0}}return c};
var qJa=/^NOTE/,pJa=/(?:\r\n|\r|\n){2,}/,r3=/^((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})[\t ]+--\x3e[\t ]+((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})(?:[\t ]*)(.*)(?:\r\n|\r|\n)/gm,rJa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.GR.ow(d3,{l:"wvppt"});g.v(f3,g.F);f3.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
f3.prototype.reset=function(){this.i&&this.i.reset()};
f3.prototype.ra=function(){g.F.prototype.ra.call(this);this.clear()};var q3={windowColor:"#080808",windowOpacity:0,textAlign:2,Fh:7,Kg:50,Xi:100,Zc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(i3,g.dM);g.k=i3.prototype;g.k.ra=function(){if(this.G||this.va){var a=this.I.ud();a&&!a.Ha()&&a.Sr()}else mJa(this,!1);g.dM.prototype.ra.call(this)};
g.k.gp=function(){if(this.Xa)return this.G||this.va;var a=r2(this.player.getAudioTrack(),s2(this.i));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?k3(this):j3(this)||k3(this)?!0:gJa(this)};
g.k.load=function(){var a=this;g.dM.prototype.load.call(this);var b=!g.R(this.i.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();this.u?(this.l&&(this.Ga.clear(),this.G?iJa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Am(this.l,"json3",function(c,d,e,f){if(c){a.u.cC()&&(a.Y=[],a.I.Ye("captions"),g.mn(a.ma),a.Ga.reset());var h=a.Ga;e=e||0;f=f||0;if(h.l.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof c){var l=new DataView(c);
8<=l.byteLength&&1718909296===l.getUint32(4)&&(l=g.$y(l,0,1835295092),c=h.l.Z("html5_fix_mdat_offset_killswitch")?c.slice(l.dataOffset,l.dataOffset+l.size):c.slice(l.dataOffset,l.offset+l.size),c3(c)||(c=g.Ze(new Uint8Array(c))))}}else c=dJa(h,c);if(c)try{if("string"!==typeof c){var m=c,n=e,p=f;if(!c3(m))throw Error("Invalid binary caption track data");h.i||(h.i=new b3(p,d));var r=h.i.l(m,n)}else{if("WEBVTT"===c.substring(0,6))d=c,p=e,h.i||(h.i=new d3),n=h.i.l(d,p),.01>Math.random()&&g.Ru(Error("Deprecated subtitles format in web player: WebVTT")),
m=n;else b:{n=c;if("{"===n[0])try{h.i||(h.i=new L2(fJa(d)));m=h.i.l(n,e);break b}catch(E){g.Qu(E);m=[];break b}p=g.$_(n);if(!p||!p.firstChild){var t=Error("Invalid caption track data");t.params=n;throw t;}if("timedtext"===p.firstChild.tagName){if(3===Number(p.firstChild.getAttribute("format"))){h.i||(h.i=new F2(fJa(d),h.l));m=h.i.l(p,e);break b}var u=Error("Unsupported subtitles format in web player (Format2)");u.params=n;throw u;}if("transcript"===p.firstChild.tagName){var x=Error("Unsupported subtitles format in web player (Format1)");
x.params=n;throw x;}var y=Error("Invalid caption track data");y.params=n;throw y;}r=m}var A=r}catch(E){g.Qu(E),h.clear(),A=[]}else A=[];a.player.Dd(A);!a.X||a.va||n3(a)||g.ND(a.i)||g.DD(a.i)||(g.rn(a.Aa),A=FIa({Fh:0,Kg:5,Xi:5,rl:2,textAlign:0,Df:0,lang:"es"}),a.Fa=[A],h=["Haz clic en "," para ir a la configuraci\u00f3n"],a.Qa||(r=new g.MJ(g.aK()),g.G(a,r),a.Qa=r.element),r=A.end-A.start,(d=g.HE(a.l))&&a.Fa.push(new B2(A.start,r,0,A.id,d)),a.Fa.push(new B2(A.start,r,0,A.id,h[0]),new B2(A.start,r,0,
A.id,a.Qa,!0),new B2(A.start,r,0,A.id,h[1],!0)),a.player.Dd(a.Fa),g.pn(a.Aa));!a.X||a.va||n3(a)||(g.eE(a.i)?(0,g.J0)(!0):o3(a,"module-enabled",!0),a.J&&(a.J.B=a.l),a.player.qp());a.X=!1}}),!b||this.G||this.va||n3(this)||this.player.Ma("captionschanged",g.IE(this.l))),b||(this.l&&!n3(this)?this.player.Ma("captionschanged",g.IE(this.l)):this.player.Ma("onCaptionsTrackListChanged"))):(this.u=hJa(this),g.G(this,this.u),this.u.yq(function(){var c=r2(a.player.getAudioTrack(),s2(a.i)),d;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===c?j3(a)||a.X||gJa(a)?d=m3(a,a.X):k3(a)&&(d=l3(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===c?d=m3(a,a.X):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===c&&k3(a)&&(d=l3(a));if(a.G||a.va){var e=g.eM(a.u.l,!0);c=[];for(var f=0;f<e.length;f++){var h=e[f],l=g.Fe("TRACK");l.setAttribute("kind","subtitles");l.setAttribute("label",g.HE(h));l.setAttribute("srclang",g.JE(h));l.setAttribute("id",h.toString());a.va||l.setAttribute("src",a.u.qo(h,"vtt"));h===d&&l.setAttribute("default",
"1");c.push(l)}d=a.I.ud();d.Jr(c);d=d.ue();a.Ya&&a.xa.N(d.textTracks,"change",a.IR)}else!a.l&&d&&p3(a,d),a.player.Ma("onCaptionsTrackListChanged"),a.player.Ma("onApiChange")}))};
g.k.unload=function(){this.G&&this.l?iJa(this,!1):(this.Aa&&g.rn(this.Aa),this.player.Ye("captions"),this.Y=[],this.u&&this.u.zl(),this.Ga.clear(),this.L&&this.player.Dd(this.L),this.hD());g.dM.prototype.unload.call(this);this.player.qp();this.player.Ma("captionschanged",{})};
g.k.create=function(){this.gp()&&this.load()};
g.k.IR=function(){for(var a=this.I.ud().ue().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.eM(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.l:null)!==b&&p3(this,b,!0)};
g.k.iT=function(){!this.l&&this.G||this.unload()};
g.k.zd=function(a){this.Y.push(a);g.mn(this.ma)};
g.k.We=function(a){g.lb(this.Y,a);this.u instanceof v2&&this.u.G&&this.player.Nf([a]);g.mn(this.ma)};
g.k.mS=function(a){if(a instanceof C2){var b=this.V[a.id];b&&b.l!==a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=kJa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Da[b]||(this.Da[b]=[]),this.Da[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Na.element.id};
g.k.sS=function(){lJa(this,this.Fa);this.Fa=null};
g.k.fD=function(){var a=this;this.ma.stop();g.Qb(this.Da);this.Y.sort(g.Xv);var b=this.Y;if(this.L){var c=g.Ke(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.Ab(b,this.mS,this);g.Cb(this.V,function(d,e){a.Da[e]?(d.element.parentNode||(d instanceof A2||d instanceof z2||g.Fb(a.V,function(f,h){h!==e&&f.l.params.Fh===d.l.params.Fh&&f.l.params.Kg===d.l.params.Kg&&f.l.params.Xi===d.l.params.Xi&&(f.dispose(),delete a.V[h]);return h===e},a),jJa(a,d.element)),d.Nq(a.Da[e])):(d.dispose(),delete a.V[e])},this)};
g.k.wS=function(){g3(this,{},!0);g.R(this.i.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ma("captionssettingschanged")};
g.k.GN=function(){var a=q3.Zc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Di?3:a.bold?1:a.Di?2:0,textOpacity:a.textOpacity,windowColor:q3.windowColor,windowOpacity:q3.windowOpacity};var b=h3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.YJ=function(a,b){var c={};g.Ra(c,h3(this,"display-settings"));g.Ra(c,a);g3(this,c,b);this.player.Ma("captionssettingschanged")};
g.k.hD=function(){!this.G&&this.loaded&&(g.Cb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.fD())};
g.k.Oe=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.de(b,-2,4);this.YJ({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&p3(this,this.l,!0);break;case "stickyLoading":void 0!==b&&this.i.u&&(g.eE(this.i)?(0,g.J0)(!!b):o3(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.G)break;if(!g.Na(b))break;if(g.Pb(b)){p3(this,null,!0);break}a=g.eM(this.u.l,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?mIa(e,b.translationLanguage):e)}!c||c===this.l&&this.loaded||(b=(0,g.Joa)(),a=g.JE(c),b.length&&a===b[b.length-1]||(b.push(a),(0,g.jGa)(b)),p3(this,c,!0))}else return this.loaded&&this.l&&!n3(this)?g.IE(this.l):{};return"";case "tracklist":return this.u?g.Pc(g.eM(this.u.l,!(!b||!b.includeAsr)),function(f){return g.IE(f)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.G||void 0===b||mJa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.i.u&&a.push("stickyLoading");return a};
g.k.IA=function(){var a=this.l;return a?{cc:a.vssId}:{}};
g.k.WS=function(){this.loaded&&this.l&&!n3(this)?(g.eE(this.i)?(0,g.J0)(!1):o3(this,"module-enabled",!1),this.unload(),k3(this,!0)&&p3(this,l3(this),!1)):this.HJ()};
g.k.HJ=function(){this.loaded&&this.l||p3(this,n3(this)||!this.l?m3(this,!0):this.l,!0)};
g.k.tP=function(){var a=n3(this);k3(this,a)?p3(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.gp()&&(a?p3(this,m3(this),!1):this.load()))};
g.GR.ow(i3,{fD:"smucd"});g.oM.captions=i3;})(_yt_player);
