(function(g){var window=this;'use strict';var zJa=function(a,b){a.Ma("onAutonavCoundownStarted",b)},F3=function(a,b,c){var d=b.fb();
g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Ge(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.FF&&(b.lengthText?(f=b.lengthText||null,h=b.Dw||null):b.lengthSeconds&&(f=g.LK(b.lengthSeconds),h=g.LK(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.VL(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.FF?b.isLivePlayback:null,n=b instanceof g.FF?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.Kr||g.xH("Ver $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.lm(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.Nr};b instanceof g.WL&&(d.playlist_length=b.length);a.update(d)},G3=function(a){var b=a.T(),c=b.l;
g.V.call(this,{D:"a",K:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.G:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",Ca:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ca:["ytp-autonav-timestamp"],oa:"{{duration}}"},{D:"div",Ca:["ytp-autonav-live-stamp"],oa:"En directo"},
{D:"div",Ca:["ytp-autonav-upcoming-stamp"],oa:"Pr\u00f3ximamente"},{D:"div",K:"ytp-autonav-list-overlay",S:[{D:"div",K:"ytp-autonav-mix-text",oa:"Mix"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",Ca:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],oa:"{{title}}"},{D:"div",Ca:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],oa:"{{author}}"},{D:"div",Ca:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],oa:"{{views_and_publish_time}}"}]});this.I=
a;this.suggestion=null;this.i=c;this.Pa("click",this.onClick);this.Pa("keypress",this.l)},I3=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;b=a.T();var d=b.l;this.I=a;this.suggestion=null;this.i=new g.V({D:"div",K:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",oa:"{{autoplayAlternativeHeader}}"},
{D:"a",K:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:d?b.G:""},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ca:["ytp-autonav-timestamp"],oa:"{{duration}}"},{D:"div",Ca:["ytp-autonav-live-stamp"],oa:"En directo"},{D:"div",Ca:["ytp-autonav-upcoming-stamp"],oa:"Pr\u00f3ximamente"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",S:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",
oa:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",oa:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",oa:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",oa:"{{author_and_views}}"}]}]}]});g.G(this,this.i);this.i.ya(this.element);d||this.N(this.i.Ba("ytp-autonav-endscreen-link-container"),"click",this.aE);this.I.ac(this.element,this,115127);this.I.ac(this.i.Ba("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({D:"div",K:"ytp-autonav-overlay"});
g.G(this,this.overlay);this.overlay.ya(this.element);this.u=new g.V({D:"div",K:"ytp-autonav-endscreen-button-container"});g.G(this,this.u);this.u.ya(this.element);this.cancelButton=new g.V({D:"button",Ca:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},oa:"Cancelar"});g.G(this,this.cancelButton);this.cancelButton.ya(this.u.element);this.cancelButton.Pa("click",this.OL,this);this.I.ac(this.cancelButton.element,
this,115129);this.playButton=new g.V({D:"a",Ca:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente v\u00eddeo"},oa:"Ver ahora"});g.G(this,this.playButton);this.playButton.ya(this.u.element);this.playButton.Pa("click",this.aE,this);this.I.ac(this.playButton.element,this,115130);this.B=new g.J(function(){H3(c)},500);
g.G(this,this.B);this.ZD();this.N(a,"autonavvisibility",this.ZD)},H3=function(a){var b=J3(a),c=Math,d=c.min;
var e=a.l?Date.now()-a.l:0;c=d.call(c,e,b);K3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.jh()?a.select(!0):a.jh()&&a.B.start()},J3=function(a){var b=a.I.Xn();
return 0<=b?b:g.S(a.I.T().experiments,"autoplay_time")||1E4},K3=function(a,b){b=void 0===b?-1:b;
a=a.i.Ba("ytp-autonav-endscreen-upnext-header");g.He(a);if(0<=b){b=String(b);var c="A continuaci\u00f3n en $SECONDS".match(/\$SECONDS/gi)[0],d="A continuaci\u00f3n en $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Ge("A continuaci\u00f3n en $SECONDS".slice(0,d)));var e=g.Fe("span");g.wn(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Re(e,b);a.appendChild(e);a.appendChild(g.Ge("A continuaci\u00f3n en $SECONDS".slice(d+c.length)));return}}g.Re(a,"Siguiente")},L3=function(a,b){g.V.call(this,
{D:"div",
Ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},N3=function(a){g.V.call(this,{D:"div",
Ca:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",S:[{D:"span",K:"ytp-upnext-header",oa:"Siguiente"},{D:"span",K:"ytp-upnext-title",oa:"{{title}}"},{D:"span",K:"ytp-upnext-author",oa:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente v\u00eddeo"},S:[{D:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},S:[{D:"circle",K:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",S:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",
oa:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=a;this.cancelButton=null;this.C=this.Ba("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.J(this.vv,5E3,this);this.l=0;var b=this.Ba("ytp-upnext-cancel");this.cancelButton=new g.V({D:"button",Ca:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},oa:"Cancelar"});g.G(this,this.cancelButton);this.cancelButton.Pa("click",
this.PL,this);this.cancelButton.ya(b);this.cancelButton&&this.api.ac(this.cancelButton.element,this,115129);g.G(this,this.B);this.api.ac(this.element,this,18788);b=this.Ba("ytp-upnext-autoplay-icon");this.N(b,"click",this.QL);this.api.ac(b,this,115130);this.bE();this.N(a,"autonavvisibility",this.bE);this.N(a,"mdxnowautoplaying",this.mQ);this.N(a,"mdxautoplaycanceled",this.nQ);this.N(a,"mdxautoplayupnext",this.XJ);M3(this)&&(a=(a=g.CL(this.api.rb()))?a.FN():null)&&this.XJ(a);g.L(this.element,"ytp-upnext-mobile",
this.api.T().i)},M3=function(a){return 3===a.api.getPresentingPlayerType()},AJa=function(a,b){return b?b:0<=a.api.Xn()?a.api.Xn():g.S(a.api.T().experiments,"autoplay_time")||1E4},O3=function(a,b){b=AJa(a,b);
var c=Math,d=c.min;var e=(0,g.O)()-a.l;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.C.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.jh()&&!M3(a)?a.select(!0):a.jh()&&a.i.start()},P3=function(a){L3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.V({D:"div",K:"ytp-suggestion-panel",S:[{D:"div",Ca:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],oa:"M\u00e1s v\u00eddeos"}]});this.J=new g.V({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.G=!1;this.l=new I3(this.player);g.G(this,this.l);this.l.ya(this.element);a.getVideoData().Pb?this.i=this.l:(this.i=new N3(a),g.GL(this.player,this.i.element,4),g.G(this,this.i));this.overlay=
new g.V({D:"div",K:"ytp-autonav-overlay-cancelled-state"});g.G(this,this.overlay);this.overlay.ya(this.element);this.B=new g.TL(this);g.G(this,this.B);g.G(this,this.table);this.table.ya(this.element);this.table.show();g.G(this,this.J);this.J.ya(this.table.element);this.hide()},BJa=function(a,b){return g.Pc(b.suggestions,function(c){c=g.xO(a.player.T(),c);
g.G(a,c);return c})},Q3=function(a){var b=a.Jd();
b!==a.C&&(a.C=b,a.player.W("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},R3=function(a){L3.call(this,a,"subscribecard-endscreen");
this.i=new g.V({D:"div",K:"ytp-subscribe-card",S:[{D:"img",K:"ytp-author-image",U:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",S:[{D:"div",K:"ytp-author-name",oa:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.G(this,this.i);this.i.ya(this.element);var b=a.getVideoData();this.subscribeButton=new g.kN("Suscribirme",null,"Anular suscripci\u00f3n",null,!0,!1,b.yh,b.subscribed,"trailer-endscreen",null,null,a);g.G(this,this.subscribeButton);this.subscribeButton.ya(this.i.Ba("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.La);this.La();this.hide()},S3=function(a){var b=a.T(),c=g.nB||g.mg?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Ca:e,U:{href:"{{url}}",target:d?b.G:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{D:"div",K:"ytp-videowall-still-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",S:[{D:"span",K:"ytp-videowall-still-info-bg",S:[{D:"span",K:"ytp-videowall-still-info-content",U:c,S:[{D:"span",K:"ytp-videowall-still-info-title",oa:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",
oa:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",oa:"En directo"},{D:"span",K:"ytp-videowall-still-info-duration",oa:"{{duration}}"}]}]}]},{D:"span",Ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{D:"span",K:"ytp-videowall-still-listlabel-length",S:[" (",{D:"span",oa:"{{playlist_length}}"},")"]}]},{D:"span",Ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
S:[{D:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",K:"ytp-videowall-still-listlabel-length",oa:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.TL(this);g.G(this,this.i);this.Pa("click",this.onClick);this.Pa("keypress",this.u);this.i.N(a,"videodatachange",this.kb);a.Cg(this.element,this);this.kb()},T3=function(a){L3.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.J=!1;this.L=null;this.l=new g.TL(this);g.G(this,this.l);this.G=new g.J(function(){g.K(b.element,"ytp-show-tiles")},0);
g.G(this,this.G);var c=new g.V({D:"button",Ca:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Anterior"},S:[g.TJ()]});g.G(this,c);c.ya(this.element);c.Pa("click",this.UL,this);this.table=new g.MJ({D:"div",K:"ytp-endscreen-content"});g.G(this,this.table);this.table.ya(this.element);c=new g.V({D:"button",Ca:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Siguiente"},S:[g.UJ()]});g.G(this,c);c.ya(this.element);c.Pa("click",this.TL,this);a.getVideoData().Pb?this.i=new I3(a,!0):this.i=new N3(a);
g.G(this,this.i);g.GL(this.player,this.i.element,4);this.hide()},U3=function(a){return g.HL(a.player)&&a.Mr()&&!a.B},CJa=function(a,b){return g.Pc(b.suggestions,function(c){c=g.xO(a.I.T(),c);
g.G(a,c);return c})},V3=function(a){var b=a.Jd();
b!==a.J&&(a.J=b,a.player.W("autonavvisibility"))},W3=function(a){g.dM.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.TL(this);g.G(this,this.listeners);this.env=a.T();DJa(a)?(this.u=!0,EJa(this),this.i?this.endScreen=new P3(a):this.endScreen=new T3(this.player)):this.env.yc?this.endScreen=new R3(this.player):this.endScreen=new L3(this.player);g.G(this,this.endScreen);g.GL(this.player,this.endScreen.element,4);FJa(this);this.listeners.N(a,"videodatachange",this.kb,this);this.listeners.N(a,g.Yv("endscreen"),function(c){b.zd(c)});
this.listeners.N(a,g.Zv("endscreen"),function(c){b.We(c)})},EJa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.qf&&a.l===b.Pb)return!1;a.i=b.qf;a.l=b.Pb;return!0},DJa=function(a){a=a.T();
return a.qb&&!a.yc},FJa=function(a){a.player.Ye("endscreen");
var b=a.player.getVideoData();b=new g.Vv(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Vv(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Dd([b,c])};
g.zL.prototype.Xn=g.ca(2,function(){return this.app.Xn()});
g.tW.prototype.Xn=g.ca(1,function(){return this.getVideoData().SE});
g.v(G3,g.V);G3.prototype.select=function(){(this.I.dj(this.suggestion.fb().videoId,this.suggestion.Nd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.hA||void 0)||this.I.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.I.Gb(this.element)};
G3.prototype.onClick=function(a){g.CM(a,this.I,this.i,this.suggestion.Nd||void 0)&&this.select()};
G3.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.bq(a)||(this.select(),g.aq(a))}};
G3.prototype.je=function(a){g.L(this.element,"ytp-suggestion-card-with-margin",a)};g.v(I3,g.V);g.k=I3.prototype;g.k.Cr=function(a){this.suggestion!==a&&(this.suggestion=a,F3(this.i,a),this.playButton.Ra("url",this.suggestion.lm()),this.je())};
g.k.je=function(){var a=this.I.Ai(!0,this.I.isFullscreen());g.L(this.element,"ytp-autonav-endscreen-small-mode",this.Je(a));g.L(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.Ix);g.L(this.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.I.Jd());g.L(this.I.getRootNode(),"countdown-running",this.jh());g.L(this.element,"ytp-player-content",this.I.Jd());g.jg(this.overlay.element,{width:a.width+"px"});if(!this.jh()){this.I.Jd()?K3(this,Math.round(J3(this)/
1E3)):K3(this);a=!!this.suggestion&&!!this.suggestion.Nr;var b=this.I.Jd()||!a;g.L(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.L(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);this.u.Vb(this.I.Jd())}};
g.k.jh=function(){return 0<this.l};
g.k.Pq=function(){this.jh()||(this.l=Date.now(),H3(this),zJa(this.I,J3(this)),g.L(this.I.getRootNode(),"countdown-running",this.jh()))};
g.k.Ro=function(){this.xl();H3(this);var a=this.i.Ba("ytp-autonav-endscreen-upnext-header");a&&g.Re(a,"Siguiente")};
g.k.xl=function(){this.jh()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.xl()};
g.k.aE=function(a){g.CM(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.Gb(this.playButton.element):a.currentTarget===this.i.Ba("ytp-autonav-endscreen-link-container")&&(a=this.i.Ba("ytp-autonav-endscreen-link-container"),this.I.jb(a,!0),this.I.Gb(a)),this.select())};
g.k.OL=function(){this.I.Gb(this.cancelButton.element);g.BL(this.I,!0)};
g.k.ZD=function(){var a=this.I.Jd();this.C&&this.wb!==a&&this.Vb(a);this.je();this.I.jb(this.element,a);this.I.jb(this.cancelButton.element,a);this.I.jb(this.i.Ba("ytp-autonav-endscreen-link-container"),a);this.I.jb(this.playButton.element,a)};
g.k.Je=function(a){return 400>a.width||459>a.height};g.v(L3,g.V);g.k=L3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Mr=function(){return!1};
g.k.Jd=function(){return!1};
g.k.ZG=function(){return!1};g.v(N3,g.V);g.k=N3.prototype;g.k.vv=function(){this.notification&&(this.B.stop(),this.jc(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.Cr=function(a){this.suggestion=a;F3(this,a,"hqdefault.jpg")};
g.k.bE=function(){this.Vb(this.api.Jd());this.api.jb(this.element,this.api.Jd());this.api.jb(this.Ba("ytp-upnext-autoplay-icon"),this.api.Jd());this.cancelButton&&this.api.jb(this.cancelButton.element,this.api.Jd())};
g.k.xQ=function(){window.focus();this.vv()};
g.k.Pq=function(a){var b=this;this.jh()||(g.Wq("a11y-announce","Siguiente "+this.suggestion.title),this.l=(0,g.O)(),this.i=new g.J(function(){O3(b,a)},25),O3(this,a),zJa(this.api,AJa(this,a)));
g.zn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.jh=function(){return!!this.i};
g.k.Ro=function(){this.xl();this.l=(0,g.O)();O3(this);g.K(this.element,"ytp-upnext-autoplay-paused")};
g.k.xl=function(){this.jh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.R(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.fb(),this.vv(),this.notification=new Notification("Siguiente",{body:b.title,icon:b.Ge()}),this.u=this.N(this.notification,"click",this.xQ),this.B.start())}this.xl();this.api.nextVideo(!1,a)};
g.k.QL=function(a){!g.Qe(this.cancelButton.element,g.Xp(a))&&g.CM(a,this.api)&&(this.api.Jd()&&this.api.Gb(this.Ba("ytp-upnext-autoplay-icon")),this.select())};
g.k.PL=function(){this.api.Jd()&&this.cancelButton&&this.api.Gb(this.cancelButton.element);g.BL(this.api,!0)};
g.k.mQ=function(a){M3(this);this.show();this.Pq(a)};
g.k.XJ=function(a){M3(this);this.suggestion&&this.suggestion.fb().videoId===a.fb().videoId||this.Cr(a)};
g.k.nQ=function(){M3(this);this.xl();this.hide()};
g.k.ra=function(){this.xl();this.vv();g.V.prototype.ra.call(this)};g.v(P3,L3);g.k=P3.prototype;g.k.create=function(){L3.prototype.create.call(this);this.B.N(this.player,"appresize",this.je);this.B.N(this.player,"onVideoAreaChange",this.je);this.B.N(this.player,"videodatachange",this.kb);this.B.N(this.player,"autonavchange",this.cE);this.B.N(this.player,"autonavcancel",this.RL);this.kb()};
g.k.show=function(){L3.prototype.show.call(this);(this.G||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.BL(this.player,!1);g.HL(this.player)&&this.Mr()&&!this.u?(Q3(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Pq():3===this.videoData.autonavState&&this.i.Ro()):(g.BL(this.player,!0),Q3(this));this.je()};
g.k.hide=function(){L3.prototype.hide.call(this);this.i.Ro();Q3(this)};
g.k.je=function(){var a=this.player.Ai(!0,this.player.isFullscreen());Q3(this);this.l.je();g.L(this.element,"ytp-autonav-cancelled-small-mode",this.Je(a));g.L(this.element,"ytp-autonav-cancelled-tiny-mode",this.xw(a));g.L(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.jg(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.je(1===c%2)}}};
g.k.kb=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=BJa(this,a))&&this.suggestions.length)for(this.i.Cr(this.suggestions[0]),this.i!==this.l&&this.l.Cr(this.suggestions[0]),a=0;a<GJa.length;++a){var b=GJa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new G3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,F3(c,b));g.G(this,this.videos[a]);this.videos[a].ya(this.J.element)}}this.je()}};
g.k.cE=function(a){1===a?(this.G=!1,this.u=this.videoData.clientPlaybackNonce,this.i.xl(),this.wb&&this.je()):(this.G=!0,this.Jd()&&(2===a?this.i.Pq():3===a&&this.i.Ro()))};
g.k.RL=function(a){a?this.cE(1):(this.u=null,this.G=!1)};
g.k.Mr=function(){return 1!==this.videoData.autonavState};
g.k.Je=function(a){return(910>a.width||459>a.height)&&!this.xw(a)&&!(400>=a.width||360>=a.height)};
g.k.xw=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Jd=function(){return this.wb&&g.HL(this.player)&&this.Mr()&&!this.u};
var GJa=[1,3,2,4];g.v(R3,L3);R3.prototype.La=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.jg,author:a.author});this.subscribeButton.channelId=a.yh;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.v(S3,g.V);S3.prototype.select=function(){(this.api.dj(this.suggestion.fb().videoId,this.suggestion.Nd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.hA||void 0)||this.api.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Gb(this.element)};
S3.prototype.onClick=function(a){g.CM(a,this.api,this.l,this.suggestion.Nd||void 0)&&this.select()};
S3.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.bq(a)||(this.select(),g.aq(a))}};
S3.prototype.kb=function(){var a=this.api.getVideoData(),b=this.api.T();this.l=a.C?!1:b.l};g.v(T3,L3);g.k=T3.prototype;g.k.create=function(){L3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=CJa(this,a),this.videoData=a);this.je();this.l.N(this.player,"appresize",this.je);this.l.N(this.player,"onVideoAreaChange",this.je);this.l.N(this.player,"videodatachange",this.kb);this.l.N(this.player,"autonavchange",this.Qy);this.l.N(this.player,"autonavcancel",this.SL);a=this.videoData.autonavState;a!==this.L&&this.Qy(a);this.l.N(this.element,"transitionend",this.JR)};
g.k.destroy=function(){g.ku(this.l);g.Di(this.stills);this.stills=[];this.suggestions=null;L3.prototype.destroy.call(this);g.zn(this.element,"ytp-show-tiles");this.G.stop();this.L=this.videoData.autonavState};
g.k.Mr=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){L3.prototype.show.call(this);g.zn(this.element,"ytp-show-tiles");this.player.T().i?g.qn(this.G):this.G.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.BL(this.player,!1);U3(this)?(V3(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Pq():3===this.videoData.autonavState&&this.i.Ro()):(g.BL(this.player,!0),V3(this))};
g.k.hide=function(){L3.prototype.hide.call(this);this.i.Ro();V3(this)};
g.k.JR=function(a){g.Xp(a)===this.element&&this.je()};
g.k.je=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=this.I.Ai(!0,this.I.isFullscreen()),b=g.wL(this.I);b&&(b=b.ze()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,u=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.yg(a,m,n);g.jg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Cr(this.suggestions[0]);this.i instanceof I3&&this.i.je();g.L(this.element,"ytp-endscreen-takeover",U3(this));V3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.ee(p+this.u,l),0!==r){t=this.stills[c];t||(t=new S3(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-u-4,A=Math.floor(m*(f+r)/b)-x-4;g.rg(t.element,x,u);g.yg(t.element,A,y);g.jg(t.element,"transitionDelay",(h+f)/20+"s");g.L(t.element,"ytp-videowall-still-mini",1===r);g.L(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),u=g.xn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",F3(r,p,u),g.vD(t)&&(t=p.lm(),t=g.Id(t,g.gN("emb_rel_end")),r.Ra("url",t)),(p=(p=p.Nd)&&p.itct)&&r.api.vl(r.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Je(e.element),g.Ci(e);this.stills.length=c}};
g.k.kb=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=CJa(this,a),this.videoData=a,this.je())};
g.k.TL=function(){this.u+=this.stills.length;this.je()};
g.k.UL=function(){this.u-=this.stills.length;this.je()};
g.k.ZG=function(){return this.i.jh()};
g.k.Qy=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.xl(),this.wb&&this.je()):(this.C=!0,this.wb&&U3(this)&&(2===a?this.i.Pq():3===a&&this.i.Ro()))};
g.k.SL=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.jb(this.stills[a].element,!0);this.Qy(1)}else this.B=null,this.C=!1;this.je()};
g.k.Jd=function(){return this.wb&&U3(this)};g.v(W3,g.dM);g.k=W3.prototype;g.k.gp=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!DJa(this.player)||b;var c=a.hd||g.GD(a.B),d=this.player.ys();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Jd=function(){return this.endScreen.Jd()};
g.k.oO=function(){return this.Jd()?this.endScreen.ZG():!1};
g.k.ra=function(){this.player.Ye("endscreen");g.dM.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.RE;if(b&&b.videoId){var c=this.player.rb().qd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.vD?a=!1:(this.player.dj(b.videoId,void 0,void 0,!0,!0,b),c&&c.Ew("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.dM.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.dM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.zd=function(a){this.gp()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.We=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.kb=function(){FJa(this);this.u&&EJa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new P3(this.player):this.endScreen=new T3(this.player),g.G(this,this.endScreen),g.GL(this.player,this.endScreen.element,4))};g.oM.endscreen=W3;})(_yt_player);
